// AFEnaclSignRequestSerializer.h

#import "AFURLRequestSerialization.h"

/**
 `AFEnaclSignRequestSerializer` signs requests generated by a
 specified serializer, setting the appropriate `x-content-signature`
 header.
 */
@interface AFEnaclSignRequestSerializer : AFHTTPRequestSerializer

/**
 The serializer used to generate requests to be signed.
 */
@property (readonly, nonatomic, strong) id <AFURLRequestSerialization> serializer;

/**
 The secret key used to do the signing.
 */
@property (readonly, nonatomic, strong) unsigned char secret_key;

/**
 Creates and returns an instance of `AFEnaclSignRequestSerializer`,
 using the specified serializer to generate requests to be signed.
 */
+ (instancetype)serializerWithSerializer:(id <AFURLRequestSerialization>)serializer;

@end
